### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by Williano** [mambojuice/invoicemanager#5]
I want to contribute to the development of the project. I want to add pagination. I have created a nice print invoice page. So the view invoice or invoice detail page will be the print view and my new print page will be the new print page.

Also some suggestions i want to add :
1. You shouldn't be able to delete an invoice once it is saved in the database. You should rather invalidate it by canceling out. With this, once an invoice is created, it should take you the detail of the invoice created which would be print invoice page.

**Comment by mambojuice** [comment]
Thanks for your suggestions! Sorry it's taken me 4 months to respond (but who's counting, right?)

I think pagination becomes a slippery slope into many additional complexities. Pagination for Letter paper vs. A4 would require logic in the view, AND user-changeable settings to define page size, AND it would make sense to be flexible enough to also be adjustable for custom letterhead. In the interest of not re-inventing the wheel I think it's better to just let the native OS printing function handle pagination.

Personally I like being able to delete an invoice, it prevents old drafts for lingering and I'm one of those OCD-types that likes unnecessary things to be gone (inbox zero, baby!). That being said, I do acknowledge that not everyone is like me, and there may be a legitimate business value in never deleting drafts or even old invoices that have been paid and closed.

 My suggestion is two parts:

1. Add a new status, something like "Cancelled" or "Void"
2. Add a configuration option (in the GUI or a simple flag in settings.py) to enable/disable deleting of invoices

Because this is more of a feature request than it is an issue, I'm going to close this issue in GitHub. I'll add what I have suggested above to any future roadmap.
